### ISSUE TITLE
new need for issue

### ISSUE THREAD

**Issue by Jeff-G-commons** [toolforge/video2commons#212]
verbatim: Please file an issue in GitHub: Traceback (most recent call last): File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request rv = self.dispatch_request() ^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/app.py", line 134, in main return render_template( ^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template return _render(app, template, context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render rv = template.render(context) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render self.environment.handle_exception() File "/data/project/video2commons/www/python/venv/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception raise rewrite_traceback_stack(source=source) File "/data/project/video2commons/video2commons/frontend/templates/main.min.html", line 1, in top-level template code {% extends "base.min.html" %} {% block jscss %} {% if loggedin %}<script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/2.2.0/jquery.min.js"></script><script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script><script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/nunjucks/3.0.1/nunjucks-slim.min.js"></script><script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/qs/6.5.2/qs.min.js"></script><script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/blueimp-file-upload/9.12.5/js/vendor/jquery.ui.widget.js"></script><script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/blueimp-file-upload/9.12.5/js/jquery.fileupload.min.js"></script><link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/blueimp-file-upload/9.12.5/css/jquery.fileupload.css" rel="stylesheet">{% if config.socketio_uri %}<script src="{{ config.socketio_uri }}/socket.io.js"></script>{% endif %}<script src="config"></script><script src="i18n/{{ lang() }}"></script><script src="static/templates.min.js"></script><script src="static/video2commons.min.js"></script>{% endif %} {% endblock %} {% block content %} {% if loggedin %}<noscript>{{ _('JavascriptRequired') }}</noscript>{% else %}<form method="get" action="{{ url_for('loginredirect') }}"><center><input class="btn btn-primary btn-success btn-lg" type="submit" value="{{ _('loginOnCommons') }}"></center><input type="hidden" name="returnto" value="{{ request.url }}"></form>{% endif %} {% endblock %} ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/video2commons/frontend/templates/base.min.html", line 1, in top-level template code <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" dir="{% if lang() is rtl %}rtl{% else %}ltr{% endif %}" lang="{{ lang() }}"><head><meta http-equiv="Content-type" content="text/html;charset=UTF-8"><title>video2commons</title><link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">{% if lang() is rtl %}<link href="static/externals/bootstrap-rtl.min.css" rel="stylesheet">{% endif %}<link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.min.css" rel="stylesheet">{% block jscss %}{% endblock %}<style>body{padding-top:60px}.github-fork-ribbon{background-color:#333}</style></head><body><div class="navbar navbar-default navbar-fixed-top"><div class="container-fluid"><div class="navbar-header"><a class="navbar-brand" href="#">video2commons</a></div><ul class="nav navbar-nav navbar-{% if lang() is rtl %}left{% else %}right{% endif %}"><li><a href="https://commons.wikimedia.org/w/index.php?title=Special:MyLanguage/Commons:Video2commons&amp;uselang={{ lang() }}"><span class="glyphicon glyphicon-book"></span> {{ _('help') }}</a></li>{% if loggedin %}<li><a href="{{ url_for('logout') }}"><span class="glyphicon glyphicon-log-out"></span> {{ _('logout') }}</a></li>{% endif %}</ul></div></div><div class="container" id="content">{% block content %}{% endblock %}</div><div class="github-fork-ribbon-wrapper {% if lang() is rtl %}left{% else %}right{% endif %}-bottom"><div class="github-fork-ribbon"><a href="https://github.com/toolforge/video2commons">{{ _('forkOnGitHub') }}</a></div></div></body></html> ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/i18n.py", line 103, in translate return get(getlanguage()).get(key, '&lt;' + key + '&gt;') ^^^^^^^^^^^^^^^^^^ File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/i18n.py", line 56, in get return json.loads(redisconnection.get(i18nkey)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/__init__.py", line 339, in loads raise TypeError(f'the JSON object must be str, bytes or bytearray, ' TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by Jeff-G-commons** [comment]
The nowikid version is at https://commons.wikimedia.org/wiki/Commons_talk:Video2commons#Issue_212
