### ISSUE TITLE
Emoji in YouTube title makes it impossible to add video 

### ISSUE THREAD

**Issue by VDK** [toolforge/video2commons#99]
Example:
https://www.youtube.com/watch?v=sRJVhciMbTs
Gives me the error message
Error: An exception occurred: IOError: [Errno 9] Bad file descriptor
At the first step of the process

**Comment by zhuyifei1999** [comment]
```
Traceback (most recent call last):
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/api.py", line 271, in extract_url
    return jsonify(**do_extract_url(url))
  File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/urlextract.py", line 90, in do_extract_url
    info = youtube_dl.YoutubeDL(params).extract_info(url, download=False)
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 408, in __init__
    'Parameter outtmpl is bytes, but should be a unicode string. '
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 601, in report_warning
    self.to_stderr(warning_message)
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 519, in to_stderr
    self._write_string(output, self._err_file)
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 498, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/youtube_dl/utils.py", line 1414, in write_string
    out.write(byt)
IOError: [Errno 9] Bad file descriptor
```
Hmm...

**Comment by zhuyifei1999** [comment]
I think this is related to the recent NFS maintenance. Restarting seems to have fixed it.

**Comment by VDK** [comment]
This seems to have been a temporary huck up in the Google api

**Comment by zhuyifei1999** [comment]
Could you clarify what huck?

**Comment by VDK** [comment]
I meant to say "hiccup"
